server {
    listen 80;
    server_name 87.251.78.190;  # Внешний IP или доменное имя

    location / {
        # Проксируем все запросы на MinIO, который доступен по имени контейнера minio:9000
        proxy_pass http://minio:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
